import { writeFileSync, mkdirSync } from 'fs';
import { join } from 'path';
import { Reporter } from './Reporter.js';
import { SuiteResult, TestStatus } from '../types.js';

export class MarkdownReporter implements Reporter {
  private outputDir: string;

  constructor(outputDir: string = './test-results') {
    this.outputDir = outputDir;
  }

  onSuiteStart(_suiteName: string): void {}

  onSuiteEnd(_result: SuiteResult): void {}

  onRunComplete(
    results: SuiteResult[],
    summary: {
      totalSuites: number;
      totalTests: number;
      passed: number;
      failed: number;
      skipped: number;
    }
  ): void {
    const lines: string[] = [];

    lines.push('# Browser Automation Test Results');
    lines.push('');
    lines.push(`**Date:** ${new Date().toISOString()}`);
    lines.push(`**Status:** ${summary.failed === 0 ? 'PASSED' : 'FAILED'}`);
    lines.push('');

    lines.push('## Summary');
    lines.push('');
    lines.push('| Metric | Count |');
    lines.push('|--------|-------|');
    lines.push(`| Total Suites | ${summary.totalSuites} |`);
    lines.push(`| Total Tests | ${summary.totalTests} |`);
    lines.push(`| Passed | ${summary.passed} |`);
    lines.push(`| Failed | ${summary.failed} |`);
    lines.push(`| Skipped | ${summary.skipped} |`);
    lines.push('');

    for (const suite of results) {
      lines.push(`## Suite: ${suite.name}`);
      lines.push('');
      lines.push(`**Duration:** ${this.formatDuration(suite.duration)}`);
      lines.push('');

      lines.push('| Test | Status | Duration |');
      lines.push('|------|--------|----------|');

      for (const test of suite.tests) {
        const status = this.getStatusLabel(test.status);
        const duration = this.formatDuration(test.duration);
        lines.push(`| ${test.name} | ${status} | ${duration} |`);
      }
      lines.push('');

      const failures = suite.tests.filter((t) => t.status === TestStatus.FAILED);
      if (failures.length > 0) {
        lines.push('### Failures');
        lines.push('');
        for (const test of failures) {
          lines.push(`#### ${test.name}`);
          lines.push('');
          lines.push('```');
          lines.push(`Error: ${test.error?.message || 'Unknown error'}`);
          if (test.error?.stack) {
            lines.push('');
            lines.push(test.error.stack);
          }
          lines.push('```');
          lines.push('');
        }
      }
    }

    lines.push('---');
    lines.push('');
    lines.push('*Generated by Browser Automation Test Framework*');
    lines.push('');

    try {
      mkdirSync(this.outputDir, { recursive: true });
    } catch (_) {}

    const outputPath = join(this.outputDir, `test-results-${Date.now()}.md`);
    writeFileSync(outputPath, lines.join('\n'), 'utf-8');
    console.log(`Markdown report written to: ${outputPath}`);
  }

  private getStatusLabel(status: TestStatus): string {
    switch (status) {
      case TestStatus.PASSED: return 'PASSED';
      case TestStatus.FAILED: return 'FAILED';
      case TestStatus.SKIPPED: return 'SKIPPED';
      default: return 'UNKNOWN';
    }
  }

  private formatDuration(ms: number): string {
    if (ms < 1000) return `${ms}ms`;
    return `${(ms / 1000).toFixed(2)}s`;
  }
}
