import { writeFileSync, mkdirSync, copyFileSync, existsSync } from 'fs';
import { join, basename } from 'path';
import { Reporter } from './Reporter.js';
import { SuiteResult, TestStatus } from '../types.js';
import { ComparisonResult } from '../../visual/comparison-engine.js';

export interface VisualTestResult {
  testName: string;
  suiteName: string;
  comparison: ComparisonResult;
  status: 'passed' | 'failed';
}

export class VisualDiffReporter implements Reporter {
  private outputDir: string;
  private results: SuiteResult[] = [];
  private visualResults: VisualTestResult[] = [];
  private artifactsDir: string;

  constructor(outputDir: string = './test-results') {
    this.outputDir = outputDir;
    this.artifactsDir = join(outputDir, 'visual-diffs');
  }

  onSuiteStart(_suiteName: string): void {}

  onSuiteEnd(result: SuiteResult): void {
    this.results.push(result);
  }

  addVisualComparison(
    testName: string,
    suiteName: string,
    comparison: ComparisonResult
  ): void {
    this.visualResults.push({
      testName,
      suiteName,
      comparison,
      status: comparison.matches ? 'passed' : 'failed',
    });
  }

  onRunComplete(
    results: SuiteResult[],
    summary: {
      totalSuites: number;
      totalTests: number;
      passed: number;
      failed: number;
      skipped: number;
    }
  ): void {
    const lines: string[] = [];

    try {
      mkdirSync(this.outputDir, { recursive: true });
      mkdirSync(this.artifactsDir, { recursive: true });
    } catch (_) {}

    this.copyVisualArtifacts();

    lines.push('# Visual Regression Test Results');
    lines.push('');
    lines.push(`**Date:** ${new Date().toISOString()}`);

    const visualPassed = this.visualResults.filter((v) => v.status === 'passed').length;
    const visualFailed = this.visualResults.filter((v) => v.status === 'failed').length;
    const overallPassed = summary.failed === 0 && visualFailed === 0;

    lines.push(`**Status:** ${overallPassed ? 'PASSED' : 'FAILED'}`);
    lines.push('');

    lines.push('## Summary');
    lines.push('');
    lines.push('| Metric | Count |');
    lines.push('|--------|-------|');
    lines.push(`| Total Test Suites | ${summary.totalSuites} |`);
    lines.push(`| Total Tests | ${summary.totalTests} |`);
    lines.push(`| Passed | ${summary.passed} |`);
    lines.push(`| Failed | ${summary.failed} |`);
    lines.push(`| Skipped | ${summary.skipped} |`);
    lines.push('');

    if (this.visualResults.length > 0) {
      lines.push('## Visual Regression Summary');
      lines.push('');
      lines.push('| Metric | Count |');
      lines.push('|--------|-------|');
      lines.push(`| Total Visual Tests | ${this.visualResults.length} |`);
      lines.push(`| Matched Baseline | ${visualPassed} |`);
      lines.push(`| Visual Changes Detected | ${visualFailed} |`);
      lines.push('');
    }

    if (visualFailed > 0) {
      lines.push('## Visual Changes Detected');
      lines.push('');

      const failures = this.visualResults.filter((v) => v.status === 'failed');
      for (const failure of failures) {
        const comp = failure.comparison;
        const diffFilename = basename(comp.diffPath || '');
        const baselineFilename = basename(comp.baselinePath);
        const currentFilename = basename(comp.currentPath);

        lines.push(`### ${failure.testName}`);
        lines.push('');
        lines.push('| Property | Value |');
        lines.push('|----------|-------|');
        lines.push(`| Different Pixels | ${comp.diffPixelCount.toLocaleString()} |`);
        lines.push(`| Difference % | ${comp.diffPercentage.toFixed(4)}% |`);
        lines.push(`| Dimensions | ${comp.dimensions.width}x${comp.dimensions.height} |`);
        lines.push('');

        lines.push('| Baseline | Current | Diff |');
        lines.push('|----------|---------|------|');
        lines.push(
          `| ![Baseline](visual-diffs/${baselineFilename}) | ![Current](visual-diffs/${currentFilename}) | ![Diff](visual-diffs/${diffFilename}) |`
        );
        lines.push('');
        lines.push('---');
        lines.push('');
      }
    }

    for (const suite of results) {
      lines.push(`## Test Suite: ${suite.name}`);
      lines.push('');
      lines.push(`**Duration:** ${this.formatDuration(suite.duration)}`);
      lines.push('');

      lines.push('| Test | Status | Duration |');
      lines.push('|------|--------|----------|');

      for (const test of suite.tests) {
        const status = this.getStatusLabel(test.status);
        const duration = this.formatDuration(test.duration);
        lines.push(`| ${test.name} | ${status} | ${duration} |`);
      }
      lines.push('');
    }

    lines.push('---');
    lines.push('');
    lines.push('*Generated by Shell Browser Automation Test Framework*');
    lines.push('');

    const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
    const outputPath = join(this.outputDir, `visual-regression-${timestamp}.md`);
    writeFileSync(outputPath, lines.join('\n'), 'utf-8');
    console.log(`Visual diff report written to: ${outputPath}`);

    this.writePRSummary(summary, visualPassed, visualFailed);
  }

  private writePRSummary(
    summary: {
      totalSuites: number;
      totalTests: number;
      passed: number;
      failed: number;
      skipped: number;
    },
    visualPassed: number,
    visualFailed: number
  ): void {
    const lines: string[] = [];
    const overallPassed = summary.failed === 0 && visualFailed === 0;

    lines.push('## Browser Automation Test Results');
    lines.push('');
    lines.push(`**Status:** ${overallPassed ? 'ALL TESTS PASSED' : 'TESTS FAILED'}`);
    lines.push('');

    lines.push('| Category | Passed | Failed | Total |');
    lines.push('|----------|--------|--------|-------|');
    lines.push(`| Functional Tests | ${summary.passed} | ${summary.failed} | ${summary.totalTests} |`);
    lines.push(`| Visual Regression | ${visualPassed} | ${visualFailed} | ${this.visualResults.length} |`);
    lines.push('');

    if (visualFailed > 0) {
      lines.push('### Visual Changes Detected');
      lines.push('');
      lines.push(`${visualFailed} screenshot(s) differ from baseline. See full report for details.`);
      lines.push('');
    }

    const summaryPath = join(this.outputDir, 'pr-comment.md');
    writeFileSync(summaryPath, lines.join('\n'), 'utf-8');
  }

  private copyVisualArtifacts(): void {
    for (const visual of this.visualResults) {
      if (visual.status === 'failed') {
        const comp = visual.comparison;

        if (existsSync(comp.baselinePath)) {
          copyFileSync(comp.baselinePath, join(this.artifactsDir, basename(comp.baselinePath)));
        }
        if (existsSync(comp.currentPath)) {
          copyFileSync(comp.currentPath, join(this.artifactsDir, basename(comp.currentPath)));
        }
        if (comp.diffPath && existsSync(comp.diffPath)) {
          copyFileSync(comp.diffPath, join(this.artifactsDir, basename(comp.diffPath)));
        }
      }
    }
  }

  private getStatusLabel(status: TestStatus): string {
    switch (status) {
      case TestStatus.PASSED: return 'PASSED';
      case TestStatus.FAILED: return 'FAILED';
      case TestStatus.SKIPPED: return 'SKIPPED';
      default: return 'UNKNOWN';
    }
  }

  private formatDuration(ms: number): string {
    if (ms < 1000) return `${ms}ms`;
    return `${(ms / 1000).toFixed(2)}s`;
  }
}
